### PR TITLE
refactor: use `thiserror` instead of `anyhow`

### LINKED ISSUE #409: Request to change `anyhow` to `thiserror` (or custom error) in `grit-pattern-matcher`
Mostly because `anyhow` is meant for [application code](https://github.com/dtolnay/anyhow?tab=readme-ov-file#comparison-to-thiserror), and this forces downstream dependencies (Biome for example) to use `anyhow` to import the types and correctly handle the errors.

I wonder if you're open to changing this for a custom error or us the library `thiserror`. I am happy to send a PR too.

### PR DESCRIPTION
**Pull request by ematipico**
Closes #409

### CODE REVIEW

**Comment by ematipico** [comment]
Could you please run the CI for me? Unfortunately I can't run the tests internally because some source code requires rustc nightly for some features, which I don't have installed (the contribution guide doesn't say anything about it).

**Comment by morgante** [comment]
Unfortunately looks like tests are failing. @ematipico Do you have more info on the rustic failure you're seeing? That wasn't a deliberate decision.

**Comment by ematipico** [comment]
Sure. I've had a couple of issues:
- The absence of `rust-toolchain. tool`; hence it wasn't possible to pin the version of the toolchain of the project (it was probably using my local version, which was outdated). I solved the issue, locally.
- This is the compiler error I get when running the tests:
	```
	error[E0554]: `#![feature]` may not be used on the stable release channel
	  --> /Users/ema/.cargo/registry/src/index.crates.io-6f17d22bba15001f/io-extras-0.18.1/src/lib.rs:19:33
	   |
	19 | #![cfg_attr(can_vector, feature(can_vector))]
	   |                                 ^^^^^^^^^^
	
	error[E0554]: `#![feature]` may not be used on the stable release channel
	  --> /Users/ema/.cargo/registry/src/index.crates.io-6f17d22bba15001f/io-extras-0.18.1/src/lib.rs:20:41
	   |
	20 | #![cfg_attr(write_all_vectored, feature(write_all_vectored))]
	   |                                         ^^^^^^^^^^^^^^^^^^
	```

**Comment by arendjr** [comment]
So if I understand correctly it’s because the `io-extras` crate depends on nightly? Maybe there’s a suitable alternative for it?

**Comment by ematipico** [comment]
> So if I understand correctly it’s because the `io-extras` crate depends on nightly? Maybe there’s a suitable alternative for it?

I really don't know, to be honest. This is a dependency that is pulled by a feature called `external_functions`, which is part of the default features

**Comment by ematipico** [comment]
Any help @morgante ?

**Comment by morgante** [comment]
@ematipico I'm not sure about the root cause - do you want me to take over cleaning up this PR?

**Comment by ematipico** [comment]
The issue is caused by the feature `external_functions`, which pulls `io-extras` , which uses nightly features. Is it expected? 

By disabling that feature, I can run tests and run clippy. Can move forward with the PR, but I realised there's more work to do, especially in other crates. 

I will commit my changes so you can evaluate the entity of the changes.

**Comment by ematipico** [comment]
Hey @morgante, unfortunately the error occurred again and I can't compile the project. Not sure why.

Feel free to take over the PR whenever you want

**Comment by morgante** [comment]
Continued in https://github.com/getgrit/gritql/pull/453

**Pull request closed without merging**
