### PR TITLE
feat:  `--language` flag

### PR DESCRIPTION
**Pull request by Sambit003**
/claim #58 

## Summary by CodeRabbit

- **New Features**
	- Added a new option to specify the language when applying patterns in the command-line interface.
- **Tests**
	- Enhanced testing suite with scenarios for the new language specification feature.

### CODE REVIEW

**Comment by ilevyor** [comment]
This is a copy of another contributor's pr: https://github.com/getgrit/gritql/pull/69

**Comment by Sambit003** [comment]
@ilevyor means? I've started earlier with the feat updates.

**Comment by Sambit003** [comment]
@ilevyor Okay, I've gone through the PR you mentioned. Quite similar. Can I work on better solution than my previous?

**Comment by ilevyor** [comment]
No I've assigned the issue to the other user.

**Pull request closed without merging**
