### PR TITLE
chore(ci): attempt to fix release-plz

### PR DESCRIPTION
**Pull request by Sec-ant**
After #312 the release-plz workflow [still fails](https://github.com/getgrit/gritql/actions/runs/8967214489/job/24624285671). The error message is:

```
Error: failed to update packages

Caused by:
    0: failed to determine next versions
    1: the working directory of this project has uncommitted changes. If these files are both committed and in .gitignore, either delete them or remove them from .gitignore. Otherwise, please commit or stash these changes:
       ["resources/language-submodules/tree-sitter-php", "resources/language-submodules/tree-sitter-rust", "resources/language-submodules/tree-sitter-solidity", "resources/language-submodules/tree-sitter-sql"]
```

Those paths are pinned submodules so I have no idea how or what uncomitted changes are involved. There's a similar issue in the release-plz repo but not caused by submodules: https://github.com/MarcoIeni/release-plz/issues/1360

For now, I just enabled the `allow_dirty` field as a workaround for this error. I have tested locally the command `release-plz update` and the above errors are gone.

@arendjr If you happen to know the exact reason why the workflow fails, please feel free to shed some light. Because I'm not sure I fully understand the entire workflow of release-plz.

## Summary by CodeRabbit

- **Refactor**
	- Improved configuration settings to allow more flexible project management.
- **Bug Fixes**
	- Updated feature settings in the project’s logging system to enhance performance and integration capabilities.

### CODE REVIEW

**Comment by arendjr** [comment]
Thanks, @Sec-ant, this helps a lot!

I forgot to follow up on this, since the last release was manually published, but I also got to the point there were dirty files, just never got to the point of how to resolve that. At the least, this should help us to get a bit further with the automated releases... and hopefully fixing the workflow entirely :)

**Comment by Sec-ant** [comment]
> I also got to the point there were dirty files

Yeah I just don't understand why there will be dirty files in those submodule paths (and not all of them, just some of them). I also left a question to the author in that related issue in release-plz, waiting for response.

**Review by morgante — APPROVED** [review]
I'm not sure why it's dirty either, but I don't see any harm in this.

**Comment by Sec-ant** [comment]
FYI: `release-plz` is working properly now.

**Pull request merged**
